* **Summary of changes**


* **Please check if the PR fulfills these requirements**

- [ ] Closes #xxxx (Replace xxxx with the Github issue number)
- [ ] [Tests added and passed](https://docs.openghg.org/development/python_devel.html#testing)
- [ ] Added an entry in the latest `CHANGELOG.md` file
- [ ] Added any new requirements to `requirements.txt` and `recipes/meta.yaml`
